BUILD: Refactor libpng submodule
RPCS3/rpcs3 pull request #10238
Opened 2021-05-04 11:29 UTC by p01arst0rm

moved libpng submodule into its own directory structure

2021-05-04 12:07 UTC, p01arst0rm commented
cc @hcorion

2021-05-05 05:08 UTC, hcorion requested changes

2021-05-05 05:08 UTC, hcorion commented on 3rdparty/CMakeLists.txt
> +	add_library(3rdparty::libpng ALIAS 3rdparty_system_libpng)
The old approach of
`add_library(3rdparty::libpng ALIAS ${LIBPNG_TARGET})`
Was cleaner IMO

2021-05-05 19:58 UTC, hcorion approved these changes

2021-05-07 08:07 UTC, merged