vk: Fix scanning for upload heap types.
RPCS3/rpcs3 pull request #10912
Opened 2021-09-22 18:59 UTC by kd-11

Fixes https://github.com/RPCS3/rpcs3/issues/10910

2021-09-22 19:02 UTC, Megamouse requested changes

2021-09-22 19:02 UTC, Megamouse commented on rpcs3/Emu/RSX/VK/vkutils/device.cpp
> +		auto find_memory_type_with_property = [&memory_heap_map](VkFlags desired_flags,  VkFlags excluded_flags)
❗️

2021-09-22 19:12 UTC, Megamouse approved these changes

2021-09-22 22:45 UTC, merged

2021-09-23 05:31 UTC, Linear524 commented
Thanks for quick fix ! :) I thought PR#10900 will eat 50% of speed forever, due to new functions implementation... But hopefully there was just a small bug =)

2021-09-23 07:30 UTC, jokoputera commented
RSX Capture please