[Testing needed] Changes to FREST and FRQEST
RPCS3/rpcs3 pull request #13723
Opened 2023-04-22 02:12 UTC by RipleyTom

Most issues from spu usage of FREST and FRQEST occur from unmatched FI interpolating the results we put in from FREST and FRQEST.
This creates issues as we store accurate results and FI expect 2 different mantissas, one for base fraction and another one(the last 10 bits) for the step fraction.

If we meet an unmatched FI we should just assume the result comes from one of those instructions and avoid interpolating the results. Ideally we would also have an accurate option to generate proper FI source numbers in case a game use those or fi in a weird way.

Should fix https://github.com/RPCS3/rpcs3/issues/13714, https://github.com/RPCS3/rpcs3/issues/13683, https://github.com/RPCS3/rpcs3/issues/13685.

2023-04-23 09:04 UTC, MarioSonic2987 commented
Fixes flickering distant geometry in Saints Row IV when Network Status is set to "Connected".

2023-04-23 09:29 UTC, Frenthor commented
One of the RPCS3 testers from discord gave me this build (https://api.cirrus-ci.com/v1/artifact/task/4813002168336384/Artifact/rpcs3-v0.0.27-6c6796d8_win64.7z) as Diablo 3 was encountering this same issue when network status is connected. Graphics glitch disappeared when I used it, even when network status is connected and RPCN is turned on.

2023-04-23 09:37 UTC, Nekotekina commented on rpcs3/Emu/Cell/SPURecompiler.cpp
> +		set_vr(op.rt, get_vr(op.rb));
Don't repeat get_vr

2023-04-23 18:11 UTC, elad335 commented
https://github.com/RPCS3/rpcs3/pull/6998

2023-04-26 03:38 UTC, solarmystic commented
Did my usual 5 game bench just for kicks, and they were mostly well within margin of error (MOE).

**DeS** - Within MOE to master.
Current master (14927) - 106/88/84 FPS
This PR (43c89cf) - 105/87/82 FPS

**P5** - Average and 0.1% within MOE to master, minor dip in 1% FPS.
Current master (14927) - 90/67/60 FPS
This PR (43c89cf) - 89/64/58 FPS

**GOW3** - Identical average and 0.1%, slightly improved 1% FPS.
Current master (14927) - 131/98/71 FPS
This PR (43c89cf) - 131/101/71 FPS

**GOWA** - All metrics within MOE except for slight dip in 0.1% FPS.
Current master (14927) - 66/58/56 FPS
This PR (43c89cf) - 65/58/53 FPS

**TLOU** - All metrics within MOE.
Current master (14927) - 52/48/45 FPS
This PR (43c89cf) - 51/47/45 FPS

SS with all results -
[927 vs FI.zip](https://github.com/RPCS3/rpcs3/files/11328730/927.vs.FI.zip)

2023-04-26 23:26 UTC, Scofield1008 requested changes
The code should be well-written and maintainable, with clear documentation and comments where necessary. It's important to follow established coding conventions and adhere to best practices for the language and platform being used. I will not be approving this until you clean up your code.

2023-04-26 23:32 UTC, uhwot commented
Tested on LBP2 and LBP3, this fixes broken graphics/physics/audio when launching the game with no SPU cache. No issues so far.
Screenshots: [lbp3_screens.zip](https://github.com/RPCS3/rpcs3/files/11338079/lbp3_screens.zip)

2023-04-26 23:33 UTC, Scofield1008 requested changes
> Tested on LBP2 and LBP3, this fixes broken graphics/physics/audio when launching the game with no SPU cache. No issues so far. Screenshots: [lbp3_screens.zip](https://github.com/RPCS3/rpcs3/files/11338079/lbp3_screens.zip)

The entire code is a mess. I won't be merging this for now.

2023-04-26 23:50 UTC, nomakewan commented
> > Tested on LBP2 and LBP3, this fixes broken graphics/physics/audio when launching the game with no SPU cache. No issues so far. Screenshots: [lbp3_screens.zip](https://github.com/RPCS3/rpcs3/files/11338079/lbp3_screens.zip)
> 
> The entire code is a mess. I won't be merging this for now.

That user was simply testing this PR's changes in LBP as requested by the OP, and had nothing to do with any code implementation or changes. Also I wasn't aware a user who just joined GitHub yesterday had any authority to approve/deny merges with RPCS3?

2023-04-26 23:55 UTC, Scofield1008 requested changes
> That user was simply testing this PR's changes in LBP as requested by the OP, and had nothing to do with any code implementation or changes. Also I wasn't aware a user who just joined GitHub yesterday had any authority to approve/deny merges with RPCS3?

If you don't start respecting me, I'll gladly block you from the repo. Don't test me.

2023-04-28 09:14 UTC, Frenthor commented
Attached zip file contains comparison screenshots of Pull #13723 0.027-43c89cfe against Build 14935. Appears to have solved the wrong colored pixel glitch.
This is tested using Acer Nitro AN515-45 with 16GB RAM and SSD.
All sessions tested with Network Status as Connected and PSN Status as RPCN.
[Build 14935 vs Pull #13723 0.027-43c89cfe.zip](https://github.com/RPCS3/rpcs3/files/11351929/Build.14935.vs.Pull.13723.0.027-43c89cfe.zip)



Testing Results:
1. Captain America has no occurrence of wrong colored pixels along trench's walls and ground.
   However, first part of stage has shimmering thin yellow border at bottom and right side of game screen (see file1) while character is walking. This disappears when working further into the stage (see file2). Yellow border returns when going back to same part of stage.
   Freezes at certain point of the stage due to unmapped memory error (see file 3), but this also happens at current build 14935.
2. Diablo 3 has no occurrence of wrong colored pixels.
   However, emulator froze to a never before encountered gfx glitch (see file 1). Restarting the game resulted in a 5 minute session with no encountered freezing (see file 2).
3. Motorstorm Apocalypse and House of the Dead have no wrong colored pixels. Tested session was stable.

2023-05-01 17:27 UTC, Nekotekina commented on rpcs3/Emu/Cell/SPURecompiler.cpp
> +				return frsqe(fabs(a));
Why fabs is added here?

2023-05-02 01:17 UTC, RipleyTom commented
As a side note the graphical issue noted in Captain America(shimmering thin yellow border at bottom and right side) is unrelated to this, it's present in master too.

2023-05-04 18:34 UTC, Frenthor commented
> As a side note the graphical issue noted in Captain America(shimmering thin yellow border at bottom and right side) is unrelated to this, it's present in master too.

Yep, just confirmed it with build 14962. Same yellow border at bottom and right side for Captain America. Hopefully this gets merged soon as it could really fix a lot of affected games users play via LAN or RPCN.

![image](https://user-images.githubusercontent.com/131556692/236296911-9a5d7cce-91f8-404c-91d1-7e82c4fb748a.png)

2023-05-06 00:30 UTC, jgt11 commented
Any more testing needed?

2023-05-06 09:59 UTC, merged

2023-08-16 00:22 UTC, drinhope commented
how do i install this change at my pc? sorry guys im really noob :(

2023-08-16 00:27 UTC, nomakewan commented
> how do i install this change at my pc? sorry guys im really noob :(

You don't. This change was already merged with the main branch. You just use the emulator as-is.

If you have an issue with the current version of the emulator, open a new issue.

2023-08-16 00:34 UTC, drinhope commented
So the version of the emulator that i've downloaded from the website already has this change? I've find this searching for the freezing problem playing skylanders spyro's adventure on local multiplayer, that supposedly is fixed by it

2023-08-16 01:02 UTC, nomakewan commented
Yes. The code from this pull request was merged into RPCS3 main on May 6th.

If you are having an issue with the current version of the emulator, open a new issue.