LV2: cleanup syscall table
RPCS3/rpcs3 pull request #9106
Opened 2020-10-20 18:29 UTC by elad335

Remove "syscall names" table.

2020-10-20 19:10 UTC, Nekotekina commented
Ok but how to verify names haven't changed

2020-10-20 22:02 UTC, Nekotekina requested changes
Found some errors.

2020-10-20 22:02 UTC, Nekotekina commented on rpcs3/Emu/Cell/lv2/lv2.cpp
> +	NULL_FUNC(sys_process_exit),                //3   (0x003)
Well, made a check myself... syscall 3 should be null_func.

2020-10-20 22:02 UTC, Nekotekina commented on rpcs3/Emu/Cell/lv2/lv2.cpp
> +	NULL_FUNC(sys_bluetooth_...),                           //599 (0x257)  ROOT
598 & 599 should be null_func

2020-10-20 22:02 UTC, Nekotekina commented on rpcs3/Emu/Cell/lv2/lv2.cpp
> +	null_func,//BIND_SYSC(sys_rsxaudio_stop_process),                   //658 (0x292)
From 654 to 658 are missing, should be NULL_FUNC

2020-10-20 22:02 UTC, Nekotekina commented on rpcs3/Emu/Cell/lv2/lv2.cpp
> +	NULL_FUNC(syscall_sys_ss_get_cache_of_analog_sunset_flag), //860 (0x35C)  AUTHID
Error in name, wrong syscall_ prefix.

2020-10-20 22:02 UTC, Nekotekina commented on rpcs3/Emu/Cell/lv2/lv2.cpp
> +	NULL_FUNC(sys_ss_~utoken_if),                           //877 (0x36D)  ROOT
877 should be null_func

2020-10-21 03:26 UTC, elad335 commented
Fixed review comments.

2020-10-21 04:15 UTC, Nekotekina commented
Okay, now some syscalls are marked as NULL_FUNC but functions exist
119
386
388/392 (weird)
837
841
842
862
863
867
873
874
875

2020-10-21 04:33 UTC, Nekotekina commented
Also 659 should be null_func

2020-10-21 04:42 UTC, elad335 commented
Fixed.

2020-10-21 04:51 UTC, Nekotekina commented
Either `constexpr auto sys_sm_ring_buzzer2 = sys_sm_ring_buzzer;` or just keep two references to the same function, idk.
sys_sm_ring_buzzer2 didn't exist in original table.

2020-10-21 04:57 UTC, elad335 commented
It doesnt affect LLVM as the name exists either way, I'll go with sys_sm_ring_buzzer2 then.

2020-10-21 04:57 UTC, Nekotekina commented
Oh, it seems it was like this in PPUFunction table. If these are truly identical syscall, it may be fine to have same name.

2020-10-21 05:19 UTC, elad335 commented
Windows build rebuild. (failed with unrelated error)

2020-10-21 07:03 UTC, Nekotekina approved these changes

2020-10-21 07:04 UTC, merged