Fix vm::range_lock
RPCS3/rpcs3 pull request #9239
Opened 2020-11-10 17:29 UTC by elad335

Why do I have to suffer from all of those rewrites :think-hang:
I dont have even the power to even explain how the code works.

2020-11-10 18:23 UTC, elad335 commented
Confirmed works.

2020-11-11 01:20 UTC, Nekotekina commented
One game shouldn't really get special codepaths. At least inline version need to get some optimization. Page info array can get disclosed at this point for direct access. Thus, if Size is specified, only one page needs check. Internal function is fine.

2020-11-11 03:28 UTC, elad335 commented
Fixed.

2020-11-11 04:13 UTC, Nekotekina requested changes

2020-11-11 04:13 UTC, Nekotekina commented on rpcs3/Emu/Memory/vm_locking.h
> +		if (Size - 1 <= 15u ? !vm::check_addr(begin) : !vm::check_addr(begin, vm::page_readable, size))
Why max 16? I think it can be 4096. Plus you don't have to optimize constexpr checks.

2020-11-11 05:21 UTC, elad335 commented
Done.

2020-11-11 07:30 UTC, merged